
name: Release

on:
  # Run this from the Action tab
  workflow_dispatch:
  # Otherwise trigger when a tag is pushed
  push:
    tags: [ "*" ]

permissions:
  contents: write

jobs:
  doctest:
    uses: ./.github/workflows/doctest.yml
  build:
    runs-on: ubuntu-latest
    needs: doctest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: pip
    - name: meta data
      id: meta
      run: python windows/github-meta.py WRITE_VERSION=1
    - name: Do NOT release, just upload artifact
      uses: actions/upload-artifact@v4
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      with:
        name: "${{ steps.meta.outputs.PYPKG }}-${{ steps.meta.outputs.PKGID }}"
        path: |
          ./*
          !.git/
          !.github/
          !.env
        compression-level: 9 # maximum compression

    - name: Create zip for release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        set -x
        zipname="${{ steps.meta.outputs.PYPKG }}-${{ steps.meta.outputs.PKGID }}.zip"
        find . '(' -path ./.git -o -path ./.github ')' -prune -o ! -name "$zipname" ! -name ".git*" -type f | cut -d/ -f2- | zip -9 -D -@ "$zipname"
    - name: Upload zip to release
      if: startsWith(github.ref, 'refs/tags/')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: "${{ steps.meta.outputs.PYPKG }}-${{ steps.meta.outputs.PKGID }}.zip"
        tag: ${{ github.ref }}
        overwrite: true
        prerelease: "${{ steps.meta.outputs.PRERELEASE }}"
        body: |
          ${{ steps.meta.outputs.RELTEXT }}

